export enum PostActionTypes {
  SET_POSTS = "SET_POSTS",
  ADD_POST = "ADD_POST",
  EDIT_POST = "EDIT_POST",
  DELETE_POST = "DELETE_POST",
  SEARCH_POSTS = "SEARCH_POSTS",
  SET_EXPORT = "SET_EXPORT",
  SET_LOADING = "SET_LOADING",
  SET_ERROR = "SET_ERROR",
}

export enum CommentActionTypes {
  ADD_COMMENT = "ADD_COMMENT",
  REMOVE_COMMENT = "REMOVE_COMMENT",
  SET_COMMENTS = "SET_COMMENTS",
  SET_LOADING = "SET_LOADING",
  SET_ERROR = "SET_ERROR",
}
